spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/konkuk;
#    url: jdbc:h2:mem:konkuk;DB_CLOSE_DELAY=-1;
#    url:
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  profiles:
    active: prod

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect


logging:
  level:
    org.hibernate.SQL: debug

server:
  address: 0.0.0.0